on:
  - pull_request
  - push

name: build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-redis-4

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP tests for PHP ${{ matrix.php }}
        run: |
          ls -al
          make test-sentinel v=${{ matrix.php }}


